apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
    name: iwtc-frontend
    namespace: argocd

spec:
    project: default

    source:
        repoURL: https://github.com/dongmin3891/iwtc-frontend-new.git
        targetRevision: refactor/full-project
        path: k8s

    destination:
        server: https://kubernetes.default.svc
        namespace: iwtc

    syncPolicy:
        automated:
            prune: true
            selfHeal: true
        syncOptions:
            - CreateNamespace=true
